name: pr-validation

on:
  pull_request:
    branches: 
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run lint
        npm run test
      env:
        CI: true
  
  benchmark:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        library: [ajv, srv, sway]
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Benchmark ${{ matrix.library }}
      run: npm run bench:${{ matrix.library }}
      env:
        CI: true

    

